import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { SettingsProvider } from "../components/SettingsProvider";
import LenisProvider from "@/lib/LenisProvider";
import TransitionProvider from "@/lib/TransitionRouter"; // Add this
import SettingsPanel from "../components/SettingsPanel";
import FloatingChatbot from "@/components/FloatingBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TransitionProvider>  {/* Wrap everything */}
          <LenisProvider>
            <SettingsProvider>
              <Navbar/>
              {children}
              <FloatingChatbot/>
              <SettingsPanel/>
            </SettingsProvider>
          </LenisProvider>
        </TransitionProvider>  {/* End wrap */}
      </body>
    </html>
  );
}
